### ISSUE TITLE
Add command line actions/utility

### ISSUE THREAD

**Issue by res2k** [res2k/HDRTray#1]
The ability to toggle HDR on or off using the command line can be helpful in certain automation cases.

**Comment by petermeierrr** [comment]
I tried your tool, and really appreciate the simple HDR status tray icon.
Having command line support for on/off is one of the two things I'd like. Ideally the cmd line command would allow parameter for display number and direct on or off instead of just toggling.
This would allow me to call it  from the MSI monitor control tool, which detects start up of specific games, and allows to run a command.

**Comment by githwithit** [comment]
I just came here looking for command line capability. I run a batch file that runs various support programs before my main game starts and having hdrtray /on and hdrtray /off in the batch file would be nice. Even without CLI ability, thanks for HDRTray!

**Comment by derailius** [comment]
great tool. curious, is there a way programmatically to get the tool to display current mode via command line?

**Comment by blakie1225** [comment]
i would also love the ability for command line or for hdr to be toggled when the app is run

**Comment by res2k** [comment]
Hello all,
the latest release (https://github.com/res2k/HDRTray/releases/tag/v0.5.0) now contains a command line utility.
It's can query and change the HDR status (globally - no per-display support, sorry).
Let me know if you have any feedback.

With that, I'll close this issue.
Note that there's still #7 open for per-display support.
