### ISSUE TITLE
Not showing in tray after windows 11 Moment 2 Update

### ISSUE THREAD

**Issue by HenryAvery** [res2k/HDRTray#5]
After updating to Windows 11 Moment 2 Update KB5023706 version 22621.1413 I can no longer see the icon in the taskbar. I know they updated the taskbar in this update.

**Comment by res2k** [comment]
Hi, I just updated to KB5023706, and the icon still appears.
_However_, that same problem actually already happened with a slightly earlier KB installed, see #3, and has been fixed in the latest version, https://github.com/res2k/HDRTray/releases/tag/v0.3. Please try that and check if that resolves the issue for you.

**Comment by HenryAvery** [comment]
I thought I had the latest version, I guess I was wrong. I updated to 0.3 and it is now working again. Great tool.  Thanks for the help.
